#!/usr/bin/env bash

num_shards=5
config_port=$((10000 + $num_shards + 1))
routing_port=$(($config_port + 1))


for shard_id in $(seq 1 $num_shards)
do
  port=$((10000 + $shard_id))
  mongocmd="db.runCommand({addshard:'localhost:$port', name:'shard$port'});"
  mongo localhost:$routing_port/admin --eval "$mongocmd"
done
